name: "Multiverse Explorer - Development - Infra"

variables:
  app-name: rick-and-morty-dev-app
  resource-group: "rick-and-morty"
  location: "westus2"
  template-file: "infra/stage-dev.bicep"
  azure-service-connection: "rick-and-morty"

stages:
  - stage: Deploy
    displayName: Deploy App Service

    jobs:
      - job: Deploy
        pool:
          vmImage: ubuntu-latest

        steps:
          - checkout: self
          - task: AzureCLI@2
            inputs:
              azureSubscription: '$(azure-service-connection)'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az group create -l $(location) -n $(resource-group)
                
                az deployment group create what-if \
                  --resource-group $(resource-group) \
                  --template-file $(template-file) \
                  --parameters appName=$(app-name)
